# MagazaDenetim - magazadenetim Service
services:
- name: ${{ env "DECK_SERVICE_TAG" }}
  enabled: true
  host: appapi1.migros.com.tr
  port: 8080
  path: /
  protocol: http
  routes:

  # Login
  - name: Login
    methods:
    - POST
    paths:
    - /rest/magazadenetim/login

  # Api
  - name: Api
    methods:
    - POST
    - GET
    paths:
    - /rest/magazadenetim/api/

  # GetIsyeri
  - name: GetIsyeri
    methods:
    - POST
    - GET
    paths:
    - /rest/magazadenetim/getisyeri