_format_version: "3.0"
_workspace: ${{ env "DECK_WORKSPACE" }}

_info:
  defaults:
    service:
      connect_timeout: 60000
      read_timeout: 60000
      write_timeout: 60000
      retries: 5
    route:
      https_redirect_status_code: 426
      preserve_host: false
      path_handling: v0
      regex_priority: 0
      request_buffering: true
      response_buffering: true
      strip_path: true
      protocols:
      - http
      - https
  select_tags:
  - ${{ env "DECK_SERVICE_TAG" }}-svc
  - ${{ env "DECK_ENV_NAME" }}
